//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vmPing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("vmPing.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping.
        /// </summary>
        public static string Button_Ping {
            get {
                return ResourceManager.GetString("Button_Ping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Button_Stop {
            get {
                return ResourceManager.GetString("Button_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aliases.
        /// </summary>
        public static string Menu_Aliases {
            get {
                return ResourceManager.GetString("Menu_Aliases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always.
        /// </summary>
        public static string Menu_Always {
            get {
                return ResourceManager.GetString("Menu_Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite Sets.
        /// </summary>
        public static string Menu_FavoriteSets {
            get {
                return ResourceManager.GetString("Menu_FavoriteSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flood Host.
        /// </summary>
        public static string Menu_FloodHost {
            get {
                return ResourceManager.GetString("Menu_FloodHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Aliases.
        /// </summary>
        public static string Menu_ManageAliases {
            get {
                return ResourceManager.GetString("Menu_ManageAliases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Favorites.
        /// </summary>
        public static string Menu_ManageFavorites {
            get {
                return ResourceManager.GetString("Menu_ManageFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string Menu_Never {
            get {
                return ResourceManager.GetString("Menu_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Menu_Options {
            get {
                return ResourceManager.GetString("Menu_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popup Notifications.
        /// </summary>
        public static string Menu_PopupNotifications {
            get {
                return ResourceManager.GetString("Menu_PopupNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Current Layout to Favorites.
        /// </summary>
        public static string Menu_SaveToFavorites {
            get {
                return ResourceManager.GetString("Menu_SaveToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status History.
        /// </summary>
        public static string Menu_StatusHistory {
            get {
                return ResourceManager.GetString("Menu_StatusHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace Route.
        /// </summary>
        public static string Menu_TraceRoute {
            get {
                return ResourceManager.GetString("Menu_TraceRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When Minimized.
        /// </summary>
        public static string Menu_WhenMinimized {
            get {
                return ResourceManager.GetString("Menu_WhenMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Add Host.
        /// </summary>
        public static string Toolbar_Add {
            get {
                return ResourceManager.GetString("Toolbar_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Columns.
        /// </summary>
        public static string Toolbar_Columns {
            get {
                return ResourceManager.GetString("Toolbar_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Start All (F5).
        /// </summary>
        public static string Toolbar_StartAll {
            get {
                return ResourceManager.GetString("Toolbar_StartAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Stop All (F5).
        /// </summary>
        public static string Toolbar_StopAll {
            get {
                return ResourceManager.GetString("Toolbar_StopAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Tooltip_Close {
            get {
                return ResourceManager.GetString("Tooltip_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit alias.
        /// </summary>
        public static string Tooltip_EditAlias {
            get {
                return ResourceManager.GetString("Tooltip_EditAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open isolated view.
        /// </summary>
        public static string Tooltip_IsolatedView {
            get {
                return ResourceManager.GetString("Tooltip_IsolatedView", resourceCulture);
            }
        }
    }
}
