//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vmPing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("vmPing.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping.
        /// </summary>
        public static string Button_Ping {
            get {
                return ResourceManager.GetString("Button_Ping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Button_Stop {
            get {
                return ResourceManager.GetString("Button_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DialogButton_Cancel {
            get {
                return ResourceManager.GetString("DialogButton_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string DialogButton_Edit {
            get {
                return ResourceManager.GetString("DialogButton_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string DialogButton_New {
            get {
                return ResourceManager.GetString("DialogButton_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string DialogButton_OK {
            get {
                return ResourceManager.GetString("DialogButton_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite.
        /// </summary>
        public static string DialogButton_Overwrite {
            get {
                return ResourceManager.GetString("DialogButton_Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string DialogButton_Remove {
            get {
                return ResourceManager.GetString("DialogButton_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string DialogButton_Save {
            get {
                return ResourceManager.GetString("DialogButton_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string DialogTitle_ConfirmDelete {
            get {
                return ResourceManager.GetString("DialogTitle_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string DialogTitle_Error {
            get {
                return ResourceManager.GetString("DialogTitle_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string DialogTitle_Warning {
            get {
                return ResourceManager.GetString("DialogTitle_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an alias for.
        /// </summary>
        public static string EditAlias_AliasFor {
            get {
                return ResourceManager.GetString("EditAlias_AliasFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to down.
        /// </summary>
        public static string Email_Down {
            get {
                return ResourceManager.GetString("Email_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error.
        /// </summary>
        public static string Email_Error {
            get {
                return ResourceManager.GetString("Email_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string Email_Host {
            get {
                return ResourceManager.GetString("Email_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to up.
        /// </summary>
        public static string Email_Up {
            get {
                return ResourceManager.GetString("Email_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is.
        /// </summary>
        public static string Email_Verb {
            get {
                return ResourceManager.GetString("Email_Verb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add alias..
        /// </summary>
        public static string Error_AddAlias {
            get {
                return ResourceManager.GetString("Error_AddAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create vmPing configuration file..
        /// </summary>
        public static string Error_CreateConfig {
            get {
                return ResourceManager.GetString("Error_CreateConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create directory for vmPing configuration file..
        /// </summary>
        public static string Error_CreateDirectory {
            get {
                return ResourceManager.GetString("Error_CreateDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete alias..
        /// </summary>
        public static string Error_DeleteAlias {
            get {
                return ResourceManager.GetString("Error_DeleteAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to launch a new instance of vmPing..
        /// </summary>
        public static string Error_FailedToLaunch {
            get {
                return ResourceManager.GetString("Error_FailedToLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load aliases..
        /// </summary>
        public static string Error_LoadAlias {
            get {
                return ResourceManager.GetString("Error_LoadAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load configuration file..
        /// </summary>
        public static string Error_LoadConfig {
            get {
                return ResourceManager.GetString("Error_LoadConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read configuration file..
        /// </summary>
        public static string Error_ReadConfig {
            get {
                return ResourceManager.GetString("Error_ReadConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to upgrade configuration file..
        /// </summary>
        public static string Error_UpgradeConfig {
            get {
                return ResourceManager.GetString("Error_UpgradeConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vmPing - Error.
        /// </summary>
        public static string Error_WindowTitle {
            get {
                return ResourceManager.GetString("Error_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to write to configuration file..
        /// </summary>
        public static string Error_WriteConfig {
            get {
                return ResourceManager.GetString("Error_WriteConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        public static string ManageAliases_Alias {
            get {
                return ResourceManager.GetString("ManageAliases_Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your aliases.
        /// </summary>
        public static string ManageAliases_Header {
            get {
                return ResourceManager.GetString("ManageAliases_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string ManageAliases_Host {
            get {
                return ResourceManager.GetString("ManageAliases_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove.
        /// </summary>
        public static string ManageAliases_Warn_DeleteA {
            get {
                return ResourceManager.GetString("ManageAliases_Warn_DeleteA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from your aliases?.
        /// </summary>
        public static string ManageAliases_Warn_DeleteB {
            get {
                return ResourceManager.GetString("ManageAliases_Warn_DeleteB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aliases.
        /// </summary>
        public static string ManageAliases_WindowTitle {
            get {
                return ResourceManager.GetString("ManageAliases_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your favorites.
        /// </summary>
        public static string ManageFavorites_Header {
            get {
                return ResourceManager.GetString("ManageFavorites_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove.
        /// </summary>
        public static string ManageFavorites_Warn_DeleteA {
            get {
                return ResourceManager.GetString("ManageFavorites_Warn_DeleteA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from your favorites?.
        /// </summary>
        public static string ManageFavorites_Warn_DeleteB {
            get {
                return ResourceManager.GetString("ManageFavorites_Warn_DeleteB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string ManageFavorites_WindowTitle {
            get {
                return ResourceManager.GetString("ManageFavorites_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aliases.
        /// </summary>
        public static string Menu_Aliases {
            get {
                return ResourceManager.GetString("Menu_Aliases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite Sets.
        /// </summary>
        public static string Menu_FavoriteSets {
            get {
                return ResourceManager.GetString("Menu_FavoriteSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flood Host.
        /// </summary>
        public static string Menu_FloodHost {
            get {
                return ResourceManager.GetString("Menu_FloodHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Aliases.
        /// </summary>
        public static string Menu_ManageAliases {
            get {
                return ResourceManager.GetString("Menu_ManageAliases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Favorites.
        /// </summary>
        public static string Menu_ManageFavorites {
            get {
                return ResourceManager.GetString("Menu_ManageFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Menu_Options {
            get {
                return ResourceManager.GetString("Menu_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popup Alerts.
        /// </summary>
        public static string Menu_PopupAlerts {
            get {
                return ResourceManager.GetString("Menu_PopupAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Favorite Set.
        /// </summary>
        public static string Menu_SaveToFavorites {
            get {
                return ResourceManager.GetString("Menu_SaveToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status History.
        /// </summary>
        public static string Menu_StatusHistory {
            get {
                return ResourceManager.GetString("Menu_StatusHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traceroute.
        /// </summary>
        public static string Menu_Traceroute {
            get {
                return ResourceManager.GetString("Menu_Traceroute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms.
        /// </summary>
        public static string Milliseconds_Symbol {
            get {
                return ResourceManager.GetString("Milliseconds_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        public static string NewAlias_Alias {
            get {
                return ResourceManager.GetString("NewAlias_Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid alias..
        /// </summary>
        public static string NewAlias_Error_InvalidAlias {
            get {
                return ResourceManager.GetString("NewAlias_Error_InvalidAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid host name..
        /// </summary>
        public static string NewAlias_Error_InvalidHost {
            get {
                return ResourceManager.GetString("NewAlias_Error_InvalidHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new alias.
        /// </summary>
        public static string NewAlias_Header {
            get {
                return ResourceManager.GetString("NewAlias_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string NewAlias_Host {
            get {
                return ResourceManager.GetString("NewAlias_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid name for this favorite set..
        /// </summary>
        public static string NewFavorite_Error_InvalidName {
            get {
                return ResourceManager.GetString("NewFavorite_Error_InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new favorite set.
        /// </summary>
        public static string NewFavorite_Header {
            get {
                return ResourceManager.GetString("NewFavorite_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Hosts.
        /// </summary>
        public static string NewFavorite_SelectedHostsHeader {
            get {
                return ResourceManager.GetString("NewFavorite_SelectedHostsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a title.
        /// </summary>
        public static string NewFavorite_Title {
            get {
                return ResourceManager.GetString("NewFavorite_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already exists.  Would you like to overwrite?.
        /// </summary>
        public static string NewFavorite_Warn_AlreadyExists {
            get {
                return ResourceManager.GetString("NewFavorite_Warn_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always.
        /// </summary>
        public static string Notification_Always {
            get {
                return ResourceManager.GetString("Notification_Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string Notification_Never {
            get {
                return ResourceManager.GetString("Notification_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When Minimized.
        /// </summary>
        public static string Notification_WhenMinimized {
            get {
                return ResourceManager.GetString("Notification_WhenMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        public static string Probe_Error {
            get {
                return ResourceManager.GetString("Probe_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply  [Host unreachable].
        /// </summary>
        public static string Probe_HostUnreachable {
            get {
                return ResourceManager.GetString("Probe_HostUnreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid port number..
        /// </summary>
        public static string Probe_InvalidPort {
            get {
                return ResourceManager.GetString("Probe_InvalidPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply  [Network unreachable].
        /// </summary>
        public static string Probe_NetUnreachable {
            get {
                return ResourceManager.GetString("Probe_NetUnreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Probe_Port {
            get {
                return ResourceManager.GetString("Probe_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLOSED.
        /// </summary>
        public static string Probe_PortClosed {
            get {
                return ResourceManager.GetString("Probe_PortClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPEN.
        /// </summary>
        public static string Probe_PortOpen {
            get {
                return ResourceManager.GetString("Probe_PortOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply from.
        /// </summary>
        public static string Probe_Reply {
            get {
                return ResourceManager.GetString("Probe_Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinging.
        /// </summary>
        public static string Probe_StartPing {
            get {
                return ResourceManager.GetString("Probe_StartPing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost:.
        /// </summary>
        public static string Probe_Stat_Lost {
            get {
                return ResourceManager.GetString("Probe_Stat_Lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received:.
        /// </summary>
        public static string Probe_Stat_Received {
            get {
                return ResourceManager.GetString("Probe_Stat_Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent:.
        /// </summary>
        public static string Probe_Stat_Sent {
            get {
                return ResourceManager.GetString("Probe_Stat_Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request timed out..
        /// </summary>
        public static string Probe_Timeout {
            get {
                return ResourceManager.GetString("Probe_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve hostname..
        /// </summary>
        public static string Probe_UnableToResolve {
            get {
                return ResourceManager.GetString("Probe_UnableToResolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply  [Unreachable].
        /// </summary>
        public static string Probe_Unreachable {
            get {
                return ResourceManager.GetString("Probe_Unreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to down.
        /// </summary>
        public static string StatusChange_Down {
            get {
                return ResourceManager.GetString("StatusChange_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [error].
        /// </summary>
        public static string StatusChange_Error {
            get {
                return ResourceManager.GetString("StatusChange_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to high latency.
        /// </summary>
        public static string StatusChange_LatencyHigh {
            get {
                return ResourceManager.GetString("StatusChange_LatencyHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to normal latency.
        /// </summary>
        public static string StatusChange_LatencyNormal {
            get {
                return ResourceManager.GetString("StatusChange_LatencyNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to started.
        /// </summary>
        public static string StatusChange_Start {
            get {
                return ResourceManager.GetString("StatusChange_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stopped.
        /// </summary>
        public static string StatusChange_Stop {
            get {
                return ResourceManager.GetString("StatusChange_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to up.
        /// </summary>
        public static string StatusChange_Up {
            get {
                return ResourceManager.GetString("StatusChange_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No status history.
        /// </summary>
        public static string StatusHistory_NoChanges {
            get {
                return ResourceManager.GetString("StatusHistory_NoChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a host changes between down or up, it&apos;ll show up here.
        /// </summary>
        public static string StatusHistory_NoChangesDescription {
            get {
                return ResourceManager.GetString("StatusHistory_NoChangesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status History.
        /// </summary>
        public static string StatusHistory_WindowTitle {
            get {
                return ResourceManager.GetString("StatusHistory_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Add Host.
        /// </summary>
        public static string Toolbar_Add {
            get {
                return ResourceManager.GetString("Toolbar_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Columns.
        /// </summary>
        public static string Toolbar_Columns {
            get {
                return ResourceManager.GetString("Toolbar_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Start All (F5).
        /// </summary>
        public static string Toolbar_StartAll {
            get {
                return ResourceManager.GetString("Toolbar_StartAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Stop All (F5).
        /// </summary>
        public static string Toolbar_StopAll {
            get {
                return ResourceManager.GetString("Toolbar_StopAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Tooltip_Close {
            get {
                return ResourceManager.GetString("Tooltip_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit alias.
        /// </summary>
        public static string Tooltip_EditAlias {
            get {
                return ResourceManager.GetString("Tooltip_EditAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open isolated view.
        /// </summary>
        public static string Tooltip_IsolatedView {
            get {
                return ResourceManager.GetString("Tooltip_IsolatedView", resourceCulture);
            }
        }
    }
}
