//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vmPing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("vmPing.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping.
        /// </summary>
        public static string Button_Ping {
            get {
                return ResourceManager.GetString("Button_Ping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Button_Stop {
            get {
                return ResourceManager.GetString("Button_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DialogButton_Cancel {
            get {
                return ResourceManager.GetString("DialogButton_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string DialogButton_Edit {
            get {
                return ResourceManager.GetString("DialogButton_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string DialogButton_New {
            get {
                return ResourceManager.GetString("DialogButton_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string DialogButton_OK {
            get {
                return ResourceManager.GetString("DialogButton_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite.
        /// </summary>
        public static string DialogButton_Overwrite {
            get {
                return ResourceManager.GetString("DialogButton_Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string DialogButton_Remove {
            get {
                return ResourceManager.GetString("DialogButton_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string DialogButton_Save {
            get {
                return ResourceManager.GetString("DialogButton_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string DialogTitle_ConfirmDelete {
            get {
                return ResourceManager.GetString("DialogTitle_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string DialogTitle_Error {
            get {
                return ResourceManager.GetString("DialogTitle_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string DialogTitle_Warning {
            get {
                return ResourceManager.GetString("DialogTitle_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias for:.
        /// </summary>
        public static string EditAlias_AliasFor {
            get {
                return ResourceManager.GetString("EditAlias_AliasFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename:.
        /// </summary>
        public static string EditFavorite_Rename {
            get {
                return ResourceManager.GetString("EditFavorite_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        public static string ManageAliases_Alias {
            get {
                return ResourceManager.GetString("ManageAliases_Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Aliases.
        /// </summary>
        public static string ManageAliases_Header {
            get {
                return ResourceManager.GetString("ManageAliases_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string ManageAliases_Host {
            get {
                return ResourceManager.GetString("ManageAliases_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove.
        /// </summary>
        public static string ManageAliases_Warn_DeleteA {
            get {
                return ResourceManager.GetString("ManageAliases_Warn_DeleteA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from your aliases?.
        /// </summary>
        public static string ManageAliases_Warn_DeleteB {
            get {
                return ResourceManager.GetString("ManageAliases_Warn_DeleteB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vmPing - Aliases.
        /// </summary>
        public static string ManageAliases_WindowTitle {
            get {
                return ResourceManager.GetString("ManageAliases_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Favorites.
        /// </summary>
        public static string ManageFavorites_Header {
            get {
                return ResourceManager.GetString("ManageFavorites_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosts in Set.
        /// </summary>
        public static string ManageFavorites_HostsInSet {
            get {
                return ResourceManager.GetString("ManageFavorites_HostsInSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove.
        /// </summary>
        public static string ManageFavorites_Warn_DeleteA {
            get {
                return ResourceManager.GetString("ManageFavorites_Warn_DeleteA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from your favorites?.
        /// </summary>
        public static string ManageFavorites_Warn_DeleteB {
            get {
                return ResourceManager.GetString("ManageFavorites_Warn_DeleteB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vmPing - Favorites.
        /// </summary>
        public static string ManageFavorites_WindowTitle {
            get {
                return ResourceManager.GetString("ManageFavorites_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aliases.
        /// </summary>
        public static string Menu_Aliases {
            get {
                return ResourceManager.GetString("Menu_Aliases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always.
        /// </summary>
        public static string Menu_Always {
            get {
                return ResourceManager.GetString("Menu_Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite Sets.
        /// </summary>
        public static string Menu_FavoriteSets {
            get {
                return ResourceManager.GetString("Menu_FavoriteSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flood Host.
        /// </summary>
        public static string Menu_FloodHost {
            get {
                return ResourceManager.GetString("Menu_FloodHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Aliases.
        /// </summary>
        public static string Menu_ManageAliases {
            get {
                return ResourceManager.GetString("Menu_ManageAliases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Favorites.
        /// </summary>
        public static string Menu_ManageFavorites {
            get {
                return ResourceManager.GetString("Menu_ManageFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string Menu_Never {
            get {
                return ResourceManager.GetString("Menu_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Menu_Options {
            get {
                return ResourceManager.GetString("Menu_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popup Notifications.
        /// </summary>
        public static string Menu_PopupNotifications {
            get {
                return ResourceManager.GetString("Menu_PopupNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Current Layout to Favorites.
        /// </summary>
        public static string Menu_SaveToFavorites {
            get {
                return ResourceManager.GetString("Menu_SaveToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status History.
        /// </summary>
        public static string Menu_StatusHistory {
            get {
                return ResourceManager.GetString("Menu_StatusHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace Route.
        /// </summary>
        public static string Menu_TraceRoute {
            get {
                return ResourceManager.GetString("Menu_TraceRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When Minimized.
        /// </summary>
        public static string Menu_WhenMinimized {
            get {
                return ResourceManager.GetString("Menu_WhenMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        public static string NewAlias_Alias {
            get {
                return ResourceManager.GetString("NewAlias_Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid alias..
        /// </summary>
        public static string NewAlias_Error_InvalidAlias {
            get {
                return ResourceManager.GetString("NewAlias_Error_InvalidAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid host name..
        /// </summary>
        public static string NewAlias_Error_InvalidHost {
            get {
                return ResourceManager.GetString("NewAlias_Error_InvalidHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Alias.
        /// </summary>
        public static string NewAlias_Header {
            get {
                return ResourceManager.GetString("NewAlias_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string NewAlias_Host {
            get {
                return ResourceManager.GetString("NewAlias_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid name for this favorite set..
        /// </summary>
        public static string NewFavorite_Error_InvalidName {
            get {
                return ResourceManager.GetString("NewFavorite_Error_InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Favorite Set.
        /// </summary>
        public static string NewFavorite_Header {
            get {
                return ResourceManager.GetString("NewFavorite_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Hosts.
        /// </summary>
        public static string NewFavorite_SelectedHostsHeader {
            get {
                return ResourceManager.GetString("NewFavorite_SelectedHostsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string NewFavorite_Title {
            get {
                return ResourceManager.GetString("NewFavorite_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already exists.  Would you like to overwrite?.
        /// </summary>
        public static string NewFavorite_Warn_AlreadyExists {
            get {
                return ResourceManager.GetString("NewFavorite_Warn_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOWN.
        /// </summary>
        public static string StatusChange_Down {
            get {
                return ResourceManager.GetString("StatusChange_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ERROR].
        /// </summary>
        public static string StatusChange_Error {
            get {
                return ResourceManager.GetString("StatusChange_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UP.
        /// </summary>
        public static string StatusChange_Up {
            get {
                return ResourceManager.GetString("StatusChange_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is.
        /// </summary>
        public static string StatusChange_Verb {
            get {
                return ResourceManager.GetString("StatusChange_Verb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No status changes.
        /// </summary>
        public static string StatusHistory_NoChanges {
            get {
                return ResourceManager.GetString("StatusHistory_NoChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a host changes between down or up, it&apos;ll show up here.
        /// </summary>
        public static string StatusHistory_NoChangesDescription {
            get {
                return ResourceManager.GetString("StatusHistory_NoChangesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vmPing - Status History.
        /// </summary>
        public static string StatusHistory_WindowTitle {
            get {
                return ResourceManager.GetString("StatusHistory_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Add Host.
        /// </summary>
        public static string Toolbar_Add {
            get {
                return ResourceManager.GetString("Toolbar_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Columns.
        /// </summary>
        public static string Toolbar_Columns {
            get {
                return ResourceManager.GetString("Toolbar_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Start All (F5).
        /// </summary>
        public static string Toolbar_StartAll {
            get {
                return ResourceManager.GetString("Toolbar_StartAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Stop All (F5).
        /// </summary>
        public static string Toolbar_StopAll {
            get {
                return ResourceManager.GetString("Toolbar_StopAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Tooltip_Close {
            get {
                return ResourceManager.GetString("Tooltip_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit alias.
        /// </summary>
        public static string Tooltip_EditAlias {
            get {
                return ResourceManager.GetString("Tooltip_EditAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open isolated view.
        /// </summary>
        public static string Tooltip_IsolatedView {
            get {
                return ResourceManager.GetString("Tooltip_IsolatedView", resourceCulture);
            }
        }
    }
}
